# Generated by Django 3.0.4 on 2020-03-15 11:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('non_listed', 'No Listed')], max_length=30)),
                ('sia_path', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('skynet_url', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=220, null=True)),
                ('expiration', models.CharField(choices=[('10_MINUTES', '10 Minutes'), ('1_HOUR', '1 Hour'), ('1_DAY', '1 Day'), ('1_WEEk', '1 Week'), ('2_WEEk', '2 Weeks'), ('1_MONTH', '1 Month'), ('6_MONTH', '6 Month'), ('1_YEAR', '1 Year')], max_length=30)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), null=True, size=None)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_address', models.CharField(blank=True, default='', max_length=120)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Gist')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('gist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Gist')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sia_path', models.CharField(blank=True, default='', max_length=120)),
                ('skynet_url', models.CharField(blank=True, max_length=120, null=True)),
                ('file_name', models.CharField(blank=True, max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('gist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Gist')),
            ],
        ),
    ]
