# Generated by Django 2.2.11 on 2020-03-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
