# Generated by Django 2.2.11 on 2020-03-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_gist_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
