# Generated by Django 2.2.11 on 2020-03-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_gist_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='sia_manifest_path',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='gist',
            name='skynet_manifest_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='gist',
            name='expiration',
            field=models.CharField(choices=[('NEVER', 'Never'), ('10_MINUTES', '10 Minutes'), ('1_HOUR', '1 Hour'), ('1_DAY', '1 Day'), ('1_WEEk', '1 Week'), ('2_WEEk', '2 Weeks'), ('1_MONTH', '1 Month'), ('6_MONTH', '6 Month'), ('1_YEAR', '1 Year')], max_length=30),
        ),
    ]
