# Generated by Django 2.2.11 on 2020-03-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200317_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='syntax',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='gist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
