# Generated by Django 2.2.11 on 2022-11-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200318_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='skynet_url',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='sia_path',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='gist',
            old_name='sia_manifest_path',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='gist',
            old_name='skynet_manifest_url',
            new_name='manifest_cid',
        ),
        migrations.RenameField(
            model_name='gist',
            old_name='skynet_url',
            new_name='manifest_path',
        ),
        migrations.RenameField(
            model_name='gist',
            old_name='sia_path',
            new_name='path',
        ),
    ]
